version: "3.1"
#
# Optional Volumes:
#  - /opt/phabricator/conf - configuration
#  - /var/repo - code repos
#
#
services:
  phabricator:
      build: .
      links: 
        - database
      ports: 
        - 8081:80

  database:
      image: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes

