version: "3.1"
services:
  phabricator:
    build: ./app
    volumes:
      - app-volume:/app

  nginx:
    build: ./nginx-php-fpm
    depends_on:
      - database
    ports:
      - 8080:80
      - 443
    volumes:
      - app-volume:/app

  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeit
      - MYSQL_USER=mallory
      - MYSQL_PASSWORD=changeit
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306

volumes:
  app-volume:

